name: CollaborativeDoc

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: collab
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7.0.5-alpine 
    expose:
      - 6379
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - .:/backend
    environment: 
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=collab
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHANNELS_URLS=redis://localhost:6379/0
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/backend
    depends_on:
      - backend
  adminer:
    image: adminer
    ports:
     - 8080:8080
volumes:
  db_data:
